from random import randint, randrange

with open('message.txt', 'r') as file:
	msg = ''.join(filter(str.isalpha, file.read().strip().upper()))

def caesar(a, key):
	return chr(((ord(a) - 0x41 + key) % 26) + 0x41)

keys = [randrange(26) for _ in range(randint(5, 10))]
enc  = []
for i, c in enumerate(msg):
	enc.append(caesar(c, keys[i % len(keys)]))

print(''.join(enc))
# LMAPVMGYZGYUOVMVIAXWKQMUZQUWMAWWFCKIBJPIAWEVUFEINIAWJSSKWNWSBMVIKTFFHWHQVLXBWEBVVTOQMECUDOLETMHRCMXIRWBSLEZVZTWVCWWRDCOEXRSUHSVBUDUFWQIFLEILSNCWFZWWJQUASJWZKNXHALMCYTDWSXNLUJWRXWAIIYEZKUJCAXAWNQFLLQUPIFWETNFSFSDGCUOKSCMXLDHZSCIOJVWVMCYUOHTTGZYBSTXNLJOJXAVOUMSVMUAYZDHMNPSWGYAGUEIYLBJPIASHMOLXIFKZAPMOFRIGHJCFIVQDJVARSCIEILXPGZCSDPBJHJKSJBUAXFGYOJAXSSMZKUJCQSCTUEGWMUCNYBWXPGKUZAKPVMKZYSTFLDQGPWTHJWGRWHAXSLEZVPCGWVQQBIZQVCPUYBYSCVVVHZMVIZJCLITNPDVWVMUVYUMIAUDYHZSCVMKFLLMTHTCZIZGZOCMVNNHWWUXNOVHSDMSGCYUWRMTLJOJX
