enc = b"LMAPVMGYZGYUOVMVIAXWKQMUZQUWMAWWFCKIBJPIAWEVUFEINIAWJSSKWNWSBMVIKTFFHWHQVLXBWEBVVTOQMECUDOLETMHRCMXIRWBSLEZVZTWVCWWRDCOEXRSUHSVBUDUFWQIFLEILSNCWFZWWJQUASJWZKNXHALMCYTDWSXNLUJWRXWAIIYEZKUJCAXAWNQFLLQUPIFWETNFSFSDGCUOKSCMXLDHZSCIOJVWVMCYUOHTTGZYBSTXNLJOJXAVOUMSVMUAYZDHMNPSWGYAGUEIYLBJPIASHMOLXIFKZAPMOFRIGHJCFIVQDJVARSCIEILXPGZCSDPBJHJKSJBUAXFGYOJAXSSMZKUJCQSCTUEGWMUCNYBWXPGKUZAKPVMKZYSTFLDQGPWTHJWGRWHAXSLEZVPCGWVQQBIZQVCPUYBYSCVVVHZMVIZJCLITNPDVWVMUVYUMIAUDYHZSCVMKFLLMTHTCZIZGZOCMVNNHWWUXNOVHSDMSGCYUWRMTLJOJX"

import itertools as it

def op(x, k): return (x-0x41 + k) % 26 + 0x41
def decode(key): return bytes(op(x, k) for x, k in zip(enc, it.cycle(key)))
crib = b"ICTF"

with open("out.txt", 'w') as f:

	def part1():
		for i in range(len(enc)-4):
			key4 = [(x-y) for x,y in zip(crib, enc[i:i + 4])]
			for sz in range(5, 11):
				key = key4 + [0]*(sz-4)
				key = [key[(j-i)%sz] for j in range(sz)]
				out = decode(key)
				if b"TART" in out and b"APPL" in out:
					print(f"{key = }")
					print(f"{out = }\n")
				f.write(out.decode() + "\n")
	part1()

	key = [-4, -8, 0, 0, 0, -14, -18]
	out1 = b'HEAPVYOURGYUADINIAXISMEUZQGEISWWFOSETJPIMEANUFEUVESWJSESSFWSBYDECTFFTEDIVLXNEATVVTAYIWCUDATALMHROUTARWBETARVZTIDYOWRDOWAPRSUTARTUDUREMAFLEUTOFCWFLESBQUAERSRKNXTIHECYTPEOPNLUVENPWAIUGARKUJOITSWNQRTHIUPIREALNFSRAZYCUOWAYEXLDTHOUIOJHERECYUAPPLGZYNAPPNLJARTSVOUYAREUAYLLDENPSIOUSGUEUGHTJPIMADEOLXUNGRAPMANNAGHJONENQDJHINKCIEUTTHGZCELLTJHJWAFTUAXROUGJAXEAIRKUJOYOUTUESEIMCNYNETHGKULIGHVMKLGOLFLDCOLOTHJIONOHAXETARVPCSERIQBILYRUPUYNGOUVVVTHINIZJOTELNPDHEREUVYGUESUDYTHOUVMKRTHETHTOHERGZOOURFNHWICTFOVHELIKGCYGENETLJART'
	E = out1.find(b"APPL")
	key[2] = b"E"[0] - out1[E + 4]
	out = decode(key)
	print(f"With APPLE:\n{out = }\n")

	def part2():
		for xy in it.product(range(26),repeat=2):
			key[3:5] = xy
			out = decode(key)
			if b"FLAG" in out:
				print(f"Found FLAG:\n{out = }")
			f.write(out.decode() + "\n")
	part2()

best_match = b"HEYIFYOUREREADINGTHISMESSAGEISUPPOSETHISMEANSYOUVESUCCESSFULLYDECRYPTEDITEHNEATTODAYIWANNATALKABOUTAPPLETARTSDIDYOUKNOWAPPLETARTSWEREMADEOUTOFAPPLESBONKERSRIGHTIHEARDPEOPLEEVENPUTSUGARINTOITSUGARTHISISREALLYCRAZYANYWAYEVENTHOUGHTHEREAREAPPLESINAPPLETARTSTHEYARESTILLDELICIOUSENOUGHTHISMADEMEHUNGRYIWANNAEATONENOWTHINKABOUTTHESMELLTHATWAFTSTHROUGHTHEAIRINTOYOURNOSEIMAGINETHEDELIGHTFULGOLDENCOLORATIONOFTHETARTIMSERIOUSLYRUNNINGOUTOFTHINGSTOTELLINHERESOIGUESSWITHOUTFURTHERADOHERESYOURFLAGICTFMORELIKEVIGENERETART"
