// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupExperimentPrefs.browser.partnerlink.useAttributionURL", true);
user_pref("app.normandy.startupExperimentPrefs.browser.search.experiment", "amazondotcom-adm");
user_pref("app.normandy.startupExperimentPrefs.browser.topsites.experiment.ebay-2020-1", true);
user_pref("app.normandy.startupExperimentPrefs.browser.topsites.useRemoteSetting", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.profileCreationThreshold", "1896163212345");
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.provider-steering.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.provider-steering.provider-list", "[{ \"name\": \"comcast\", \"canonicalName\": \"doh-discovery.xfinity.com\", \"uri\": \"https://doh.xfinity.com/dns-query\" }]");
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "11dcb205-5f55-4f35-838c-6a2ba7fa8601");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1620697366);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1620697342);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1620697606);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1620697486);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1620697396);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{6487906b-2b22-484e-8103-ddba049422a6}");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1620697335);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3e36efbf-0060-466a-95e8-0166cb823340}");
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.protections_panel.infoMessage.seen", true);
user_pref("browser.region.update.updated", 1620697338);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1620697371606");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1620699179606");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1620697344157");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1620718944157");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1620697340");
user_pref("browser.startup.homepage_override.buildID", "20210415204500");
user_pref("browser.startup.homepage_override.mstone", "88.0");
user_pref("browser.startup.lastColdStartupCheck", 1620697337);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1620697340107");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("dom.push.userAgentID", "9cffa402616f4a6a8ae508a7739567dd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210415204500");
user_pref("extensions.lastAppVersion", "88.0");
user_pref("extensions.lastPlatformVersion", "88.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8bf98ccd-c642-4aa9-b635-722a8f718bc8\",\"formautofill@mozilla.org\":\"5b12bd4d-e342-47b4-ba78-54ba0a246186\",\"pictureinpicture@mozilla.org\":\"51221573-6719-4d59-a1bb-376a00cbd5e3\",\"screenshots@mozilla.org\":\"ffa0f42a-7256-40f8-9210-eb9782fa6b6d\",\"webcompat-reporter@mozilla.org\":\"4f955dad-6587-4ff8-a256-88cb84f98f87\",\"webcompat@mozilla.org\":\"8f77fe13-f72f-48ed-82c7-85b20784b1f8\",\"default-theme@mozilla.org\":\"770333db-aae1-4601-9b56-6b048e34bbde\",\"google@search.mozilla.org\":\"c9ff911b-e24e-41a8-a8d0-25c24a4be6d3\",\"amazondotcom@search.mozilla.org\":\"c114b322-aadf-4a35-97ca-747d92056d7f\",\"wikipedia@search.mozilla.org\":\"3a160715-79ac-4a56-8c9b-d38989ecda42\",\"bing@search.mozilla.org\":\"1cb05367-9e1b-421b-a628-7f7ee72ee0c1\",\"ddg@search.mozilla.org\":\"700a3a4a-5a5c-4502-a465-1a50d5816eb6\",\"ebay@search.mozilla.org\":\"d2397adf-0365-4f62-a6ec-ec5422b972f8\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1620697342);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.decoder-doctor.MediaPlatformDecoderNotFound.formats", "video/mp4, video/mp4;codecs=\"avc1.4D401E\";width=\"640\";height=\"360\", video/mp4;codecs=\"avc1.4D401F\";width=\"854\";height=\"480\", video/mp4;codecs=\"avc1.4D401F\";width=\"1280\";height=\"720\", video/mp4;codecs=\"avc1.4D401E\", audio/mp4;codecs=\"mp4a.40.2\"");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8f6a2982-1da1-45b5-a80f-b31d9017753f");
user_pref("security.sandbox.plugin.tempDirSuffix", "3b88b020-ff10-461d-823e-11faee509a98");
user_pref("toolkit.startup.last_success", 1620697335);
user_pref("toolkit.telemetry.cachedClientID", "1bcb4c59-0f88-41de-9b99-2f9ac600b23f");
user_pref("toolkit.telemetry.previousBuildID", "20210415204500");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
